### ISSUE TITLE
Column Gap Doesn't Appear in Marbot

### ISSUE THREAD

**Issue by LauraWilson040** [LauraWilson040/modularity-mindfulness#3]
- My column gaps appear on Chrome and Firefox, but not in Markbot. Would this be a coding issue? Or a glitch with Markbot itself? @hellachella @mackenzierose
<img width="1792" alt="Screen Shot 2020-09-30 at 8 59 30 AM" src="https://user-images.githubusercontent.com/55108851/94688226-4b66b080-02fb-11eb-9322-b2abc888e799.png">
<img width="1792" alt="Screen Shot 2020-09-30 at 8 59 32 AM" src="https://user-images.githubusercontent.com/55108851/94688235-4c97dd80-02fb-11eb-8f7f-f1e07ea60b36.png">
<img width="1680" alt="Screen Shot 2020-09-30 at 9 00 27 AM" src="https://user-images.githubusercontent.com/55108851/94688315-69341580-02fb-11eb-97e3-35ee79d36860.png">

**Comment by MacKenzieRose** [comment]
Hey!

So, no, it's actually not an issue with Markbot. The spacing in-between your 3 sections at the bottom is coming from your `section` code (~line 238). However, if you inspect your code in your browser (see screenshot below), what you'll see is that you have a one column grid, which Markbot knows can't have space between the columns...because there's only one column.

<img width="757" alt="Screen Shot 2020-09-30 at 8 18 17 AM" src="https://user-images.githubusercontent.com/19557909/94690999-671b8800-02f6-11eb-9de1-02ead8cd3ac5.png">

Take a look, and re-tag me if you need any help fixing it 😄
